-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customers"
(
    cnum integer NOT NULL,
    cname text NOT NULL,
    city text NOT NULL,
    rating integer NOT NULL,
    snum integer NOT NULL,
    CONSTRAINT "Customers_pkey" PRIMARY KEY (cnum)
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    onum integer NOT NULL,
    amt numeric NOT NULL,
    odate date NOT NULL,
    cnum integer NOT NULL,
    snum integer NOT NULL,
    CONSTRAINT "Orders_pkey" PRIMARY KEY (onum)
);

CREATE TABLE IF NOT EXISTS public."Salers"
(
    snum integer NOT NULL,
    sname text NOT NULL,
    city text NOT NULL,
    comm numeric NOT NULL,
    CONSTRAINT "Salers_pkey" PRIMARY KEY (snum)
);

ALTER TABLE IF EXISTS public."Orders"
    ADD FOREIGN KEY (snum)
    REFERENCES public."Salers" (snum) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders"
    ADD FOREIGN KEY (cnum)
    REFERENCES public."Customers" (cnum) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;