working_months:
  - OCTOBER
  - NOVEMBER
  - DECEMBER
working_days:
  - "Monday, Tuesday, Wednesday, Thursday, Friday"
  - "Monday, Tuesday, Thursday, Friday"
  - "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday"
working_hours:
  - "09:00 - 17:00"
  - "08:00 - 20:00"
  - "10:00 - 18:00"
working_countries:
  - Ukraine
  - Australia
  - United States

