INSERT INTO public."Skills"(id, name) VALUES (1, 'Java');
INSERT INTO public."Skills"(id, name) VALUES (2, 'Python');
INSERT INTO public."Skills"(id, name) VALUES (3, 'JavaScript');
INSERT INTO public."Skills"(id, name) VALUES (4, 'C++');
INSERT INTO public."Skills"(id, name) VALUES (5, 'SQL');
INSERT INTO public."Skills"(id, name) VALUES (6, 'HTML');
INSERT INTO public."Skills"(id, name) VALUES (7, 'CSS');
INSERT INTO public."Skills"(id, name) VALUES (8, 'Ruby');
INSERT INTO public."Skills"(id, name) VALUES (9, 'PHP');
INSERT INTO public."Skills"(id, name) VALUES (10, 'Swift');
INSERT INTO public."Skills"(id, name) VALUES (11, 'C#');
INSERT INTO public."Skills"(id, name) VALUES (12, 'Perl');
INSERT INTO public."Skills"(id, name) VALUES (13, 'Kotlin');
INSERT INTO public."Skills"(id, name) VALUES (14, 'React');
INSERT INTO public."Skills"(id, name) VALUES (15, 'Angular');
INSERT INTO public."Skills"(id, name) VALUES (16, 'Vue.js');
INSERT INTO public."Skills"(id, name) VALUES (17, 'Node.js');
INSERT INTO public."Skills"(id, name) VALUES (18, 'Ruby on Rails');
INSERT INTO public."Skills"(id, name) VALUES (19, 'Django');
INSERT INTO public."Skills"(id, name) VALUES (20, 'Spring Framework');
INSERT INTO public."Skills"(id, name) VALUES (21, 'ASP.NET');
INSERT INTO public."Skills"(id, name) VALUES (22, 'Laravel');
INSERT INTO public."Skills"(id, name) VALUES (23, 'Express.js');
INSERT INTO public."Skills"(id, name) VALUES (24, 'MongoDB');
INSERT INTO public."Skills"(id, name) VALUES (25, 'MySQL');
INSERT INTO public."Skills"(id, name) VALUES (26, 'PostgreSQL');
INSERT INTO public."Skills"(id, name) VALUES (27, 'Oracle');
INSERT INTO public."Skills"(id, name) VALUES (28, 'Android Development');
INSERT INTO public."Skills"(id, name) VALUES (29, 'iOS Development');
INSERT INTO public."Skills"(id, name) VALUES (30, 'Machine Learning');
INSERT INTO public."Skills"(id, name) VALUES (31, 'Data Science');
INSERT INTO public."Skills"(id, name) VALUES (32, 'Artificial Intelligence');
INSERT INTO public."Skills"(id, name) VALUES (33, 'Cybersecurity');
INSERT INTO public."Skills"(id, name) VALUES (34, 'Network Security');
INSERT INTO public."Skills"(id, name) VALUES (35, 'DevOps');
INSERT INTO public."Skills"(id, name) VALUES (36, 'Cloud Computing');
INSERT INTO public."Skills"(id, name) VALUES (37, 'Blockchain');
INSERT INTO public."Skills"(id, name) VALUES (38, 'Front-End Development');
INSERT INTO public."Skills"(id, name) VALUES (39, 'Back-End Development');
INSERT INTO public."Skills"(id, name) VALUES (40, 'Full-Stack Development');
INSERT INTO public."Skills"(id, name) VALUES (41, 'UI/UX Design');
INSERT INTO public."Skills"(id, name) VALUES (42, 'Mobile App Development');
INSERT INTO public."Skills"(id, name) VALUES (43, 'Web Development');
INSERT INTO public."Skills"(id, name) VALUES (44, 'Game Development');
INSERT INTO public."Skills"(id, name) VALUES (45, 'Embedded Systems');
INSERT INTO public."Skills"(id, name) VALUES (46, 'IoT Development');
INSERT INTO public."Skills"(id, name) VALUES (47, 'AR/VR Development');
INSERT INTO public."Skills"(id, name) VALUES (48, 'Database Management');
INSERT INTO public."Skills"(id, name) VALUES (49, 'Software Testing');
INSERT INTO public."Skills"(id, name) VALUES (50, 'Project Management');
